export function buildCommandNextStep({
  currentPhase,
  governanceMode = "guided",
  step = null,
  stepLabel = null,
  primaryAction = null,
  primaryDoc = null,
  primaryGoal = null,
  requiredSections = [],
  doNotDoYet = [],
  exitCriteria = [],
  afterPrimaryAction = null,
  completed = [],
  missing = [],
  blocking = [],
  recommendedNext = [],
  writebackRequired = false,
  projectionDrift = false,
  skillPackDrift = false,
  interviewRound = null,
  interviewTarget = null,
  ambiguityPercent = null,
  confirmedFacts = [],
  readinessGates = [],
  focusQuestion = null,
  writebackSections = [],
  stepAware = false,
  updatedAt = new Date().toISOString()
}) {
  return {
    currentPhase,
    governanceMode,
    step,
    stepLabel,
    primaryAction,
    primaryDoc,
    primaryGoal,
    requiredSections,
    doNotDoYet,
    exitCriteria,
    afterPrimaryAction,
    completed,
    missing,
    blocking,
    recommendedNext,
    writebackRequired,
    projectionDrift,
    skillPackDrift,
    interviewRound,
    interviewTarget,
    ambiguityPercent,
    confirmedFacts,
    readinessGates,
    focusQuestion,
    writebackSections,
    stepAware,
    updatedAt
  };
}
